### ISSUE TITLE
too bad it does nothing :)

### ISSUE THREAD

**Issue by dBabarykin** [johnmcclumpha/sketch-retain-text-color#1]
hey John!
the idea of this plugin is just brilliant, but i've never managed to make it work.
are you planning to revisit it some day maybe?

yours
Dan

**Comment by johnmcclumpha** [comment]
Hi Dan

unfortunately with some of the more recent changes to Sketch this isn't working correctly anymore.

Hopefully I'll get a chance to update it soon - keep an eye out

**Comment by dBabarykin** [comment]
cheers )
